import { useEffect, useRef, useState } from 'react';
import { data } from '../data';
import { Id } from '../components/ui';
import { CoverageMap } from '../components/CoverageMap';
import { onLink } from '../lib/router';
import { Chrome } from '../app/Chrome';

const beats = [
 {label:'Choose',title:'Choose what to protect.',caption:'A location, an earthquake threshold, and a fixed payout. The terms are recorded before anything happens.',next:'See what backs it'},
 {label:'Commit',title:'Capital backs the promise.',caption:'The pool needs enough capital. Then the agent signs a transfer with a fixed amount and beneficiary.',next:'Follow the signatures'},
 {label:'Confirm',title:'One vote is not enough.',caption:'The agent has committed. Two of three oracle keys must also sign before the network can release funds.',next:'Replay the second signature'},
 {label:'Release',title:'The second signature releases it.',caption:'Hedera executed the scheduled transfer as soon as the required signatures were present.',next:'Open the receipt'},
 {label:'Verify',title:'A policy you can verify.',caption:'The NFT points to the original terms. The payout has its own public transaction receipt.',next:'Why the agent matters'},
 {label:'Protect',title:'Oracle keys alone cannot spend.',caption:'A separate controlled experiment collected all three oracle signatures. Without the agent, the transfer stayed blocked.',next:'Try the live demo'},
];
const readStep=()=>{const n=Number(location.hash.slice(1)||1);return Number.isInteger(n)?Math.max(0,Math.min(5,n-1)):0;};
const number=(n:number,d=2)=>n.toLocaleString(undefined,{maximumFractionDigits:d});
const oracleNames=data.quote.trigger.sources;
function Geo(){return <CoverageMap lat={data.quote.location.lat} lon={data.quote.location.lon} radiusKm={100} name={data.quote.location.name} lp={false}/>;}
function Signatures({count,agent=true}:{count:number;agent?:boolean}){return <div className="replay-signatures"><div className={`replay-agent ${agent?'is-signed':''}`}><span>{agent?'✓':'−'}</span><div><strong>Pool agent</strong><small>{agent?'Transfer pre-signed':'Signature missing'}</small></div></div><div className="replay-and">AND</div><div className="replay-oracles">{oracleNames.map((name,i)=><div key={name} className={i<count?'is-signed':''}><span>{i<count?'✓':'○'}</span><strong>{name}</strong><small>{i<count?'Signed':'Not signed'}</small></div>)}</div><div className="replay-threshold"><span>{Math.min(count,2)} / 2 required oracle signatures</span><span>{agent&&count>=2?'Quorum complete':'Transfer locked'}</span></div></div>;}
function Scene({step}:{step:number}){
 if(step===0)return <div className="replay-two"><div className="replay-map"><Geo/><div className="replay-map-caption"><span>Protected area</span><strong>Armenia, Colombia</strong><small>4.53° N · 75.68° W</small></div></div><div className="replay-terms"><span className="eyebrow">Recorded offer · mainnet</span><div className="replay-price"><span>One-time premium</span><strong>{number(data.quote.premiumHbar,5)} <small>HBAR</small></strong></div><div className="replay-price payout"><span>Fixed conditional payout</span><strong>{data.quote.payoutHbar} <small>HBAR</small></strong></div><div className="replay-rules"><div><strong>M6+</strong><span>Magnitude</span></div><div><strong>100 km</strong><span>From the pin</span></div><div><strong>≤70 km</strong><span>Depth</span></div><div><strong>30 days</strong><span>Coverage window</span></div></div><Id kind="topic" id={data.terms.topicId} label="Read the recorded terms" network="mainnet"/></div></div>;
 if(step===1)return <div className="replay-two"><div className="replay-capital"><span className="eyebrow">Liquidity providers → shared pool</span><h2>A promise needs backing.</h2><div className="replay-capacity-row"><span>Before additional capital</span><strong>{number(data.guard.before.capitalTinybar/1e8)} HBAR</strong></div><div className="replay-capacity-track"><span style={{width:`${data.guard.before.capitalTinybar/data.guard.after.capitalTinybar*100}%`}}/></div><small className="replay-muted">4 HBAR requested · insufficient capacity</small><div className="replay-capacity-row"><span>After the LP deposit</span><strong>{number(data.guard.after.capitalTinybar/1e8)} HBAR</strong></div><div className="replay-capacity-track funded"><span style={{width:'100%'}}/></div><div className="replay-allocation"><span>85% of premium → pool</span><span>15% → broker</span></div><a href="/policies?view=fund" onClick={onLink} className="hs">Explore per-policy funding previews ↗</a></div><div className="replay-contract"><span className="replay-stamp">✓ Agent committed</span><span className="eyebrow">Scheduled transfer</span><strong className="replay-big">4 <small>HBAR</small></strong><dl><div><dt>From</dt><dd>Capital pool</dd></div><div><dt>To</dt><dd>Fixed beneficiary</dd></div><div><dt>Waiting for</dt><dd>2 oracle signatures</dd></div></dl><Id kind="schedule" id={data.payout.scheduleId} label="Inspect the signed schedule" network="mainnet"/></div></div>;
 if(step===2)return <div className="replay-two"><div className="replay-vote-intro"><span className="eyebrow">Controlled signature replay</span><div className="replay-vote-count">1<span>/2</span></div><h2>Still locked.</h2><p>The first oracle signed. The beneficiary has received nothing from this schedule yet.</p><Id kind="transaction" id={data.payout.signatures.find(s=>s.role==='oracle')!.consensus} label="Verify the first signature" network="mainnet"/></div><Signatures count={1}/></div>;
 if(step===3)return <div className="replay-release"><div className="replay-release-badge">✓ Quorum complete · executed on mainnet</div><div className="replay-money-path"><div><span>Capital pool</span><strong>−4 <small>HBAR</small></strong></div><div className="replay-transfer-line" aria-hidden="true"><i/><span>→</span></div><div><span>Beneficiary</span><strong>+4 <small>HBAR</small></strong></div></div><div className="replay-complete-keys"><span>✓ Agent</span><b>+</b><span>✓ USGS key</span><b>+</b><span>✓ EMSC key</span><b>=</b><strong>Payment executed</strong></div><p>No separate executor transaction. The network completes the signed transfer.</p><Id kind="transaction" id={data.payout.executedConsensus!} label="Verify the actual 4 HBAR transfer" network="mainnet"/></div>;
 if(step===4)return <div className="replay-two"><div className="replay-nft"><header><strong>◉ AIVY QUORUM</strong><span>COVER NFT /0001</span></header><h2>Armenia</h2><span>Quindío, Colombia</span><Geo/><div><span>Recorded payout</span><strong>4 <small>HBAR</small></strong></div><footer><span>✓ Paid</span><span>MAINNET RECORD</span></footer></div><div className="replay-evidence"><span className="eyebrow">A public trail, from terms to payout</span><h2>Follow the evidence.</h2>{[{n:'01',title:'Terms published',description:'Location, trigger, payout.',kind:'topic' as const,id:data.terms.topicId},{n:'02',title:'Cover NFT minted',description:'A receipt linked to those terms.',kind:'transaction' as const,id:data.policy.mintTxId},{n:'03',title:'NFT delivered',description:'Transferred to the beneficiary.',kind:'transaction' as const,id:data.policy.deliverTxId},{n:'04',title:'Payout executed',description:'4 HBAR moved on mainnet.',kind:'transaction' as const,id:data.payout.executedConsensus!}].map(r=><div className="replay-evidence-row" key={r.n}><span>{r.n}</span><div><strong>{r.title}</strong><small>{r.description}</small></div><Id kind={r.kind} id={r.id} label="Verify" network="mainnet"/></div>)}<small className="replay-muted">App presentation of the recorded NFT. Original wallet artwork is unchanged.</small></div></div>;
 return <div className="replay-protection"><div className="replay-test"><span className="eyebrow">Control experiment</span><h2>Agent + oracle quorum</h2><div className="replay-key-equation"><span>✓ Agent</span><b>+</b><span>✓ 2 oracles</span></div><strong className="replay-outcome success">Transfer executed ↗</strong><Id kind="schedule" id={data.control.scheduleId} label="Verify the successful control" network="mainnet"/></div><div className="replay-test blocked"><span className="eyebrow">Missing authorization</span><h2>Oracle quorum alone</h2><div className="replay-key-equation"><span>− Agent</span><b>+</b><span>✓ 3 oracles</span></div><strong className="replay-outcome">Transfer blocked ⊘</strong><Id kind="schedule" id={data.adversarial.scheduleId} label="Verify the blocked attempt" network="mainnet"/></div><p>This proves a key restriction. The agent and oracle quorum together still control the pool; it does not establish independent operators.</p></div>;
}
export function Story(){
 const [step,setStep]=useState(readStep), heading=useRef<HTMLHeadingElement>(null),previous=useRef(step);
 const go=(n:number)=>{const next=Math.max(0,Math.min(5,n));history.replaceState(null,'',`/story#${next+1}`);setStep(next);};
 useEffect(()=>{const sync=()=>setStep(readStep());window.addEventListener('hashchange',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('popstate',sync);};},[]);
 useEffect(()=>{if(previous.current===step)return;previous.current=step;heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});},[step]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey||(e.target as HTMLElement).closest('input,textarea,button,a,summary'))return;if(e.key==='ArrowRight'){e.preventDefault();go(step+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(step-1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[step]);
 const b=beats[step];
 return <div className="app"><Chrome route={{name:'story'}}/><main className="replay-page">
 <div className="replay-topline"><span className="eyebrow">Inside Aivy Quorum</span><span className="replay-network">● Mainnet recording</span></div>
 <nav className="replay-steps" aria-label="Demonstration steps">{beats.map((b,i)=><button key={b.label} aria-current={step===i?'step':undefined} aria-label={`Step ${i+1}: ${b.label}`} onClick={()=>go(i)}><span>{String(i+1).padStart(2,'0')}</span>{b.label}<i/></button>)}</nav>
 <div className="replay-heading"><div className="eyebrow">{String(step+1).padStart(2,'0')} / 06 · {b.label}</div><h1 ref={heading} tabIndex={-1}>{b.title}</h1><p>{b.caption}</p></div>
 <section className={`replay-scene replay-scene-${step}`} aria-label={`${b.label}: recorded demonstration`} key={step}><Scene step={step}/></section>
 <div className="replay-context"><span>Controlled demonstration · September 4, 2026</span><span>{step===2||step===3?'Signatures replayed, not a live earthquake claim.':'Live cover creation runs on testnet.'}</span></div>
 <div className="replay-navigation"><button className="chip" disabled={step===0} onClick={()=>go(step-1)}>← Previous</button>{step<5?<button className="buy compact" onClick={()=>go(step+1)}>{b.next} →</button>:<a href="/" onClick={onLink} className="buy compact">Try the live demo →</a>}</div>
 <details className="proof-details replay-details"><summary>What is live, recorded, or proposed? <span>+</span></summary><div className="replay-scope"><div><strong>Live · testnet</strong><p>Create cover, inspect NFT and schedule receipts, verify paid x402 oracle queries. Event checks are manually requested.</p><a href="/" onClick={onLink}>Create demo cover →</a></div><div><strong>Recorded · mainnet</strong><p>This six-step story replays controlled signatures and real HBAR transfers. Historical pricing differs from today’s model. This recording uses USGS, EMSC and SGC key labels; the live services use USGS, EMSC and GEOFON.</p><Id kind="schedule" id={data.payout.scheduleId} label="Inspect the recording" network="mainnet"/></div><div><strong>Proposed · policy LPs</strong><p>Explore contributions, premium income and capital at risk. Per-policy deposits and LP NFTs are previews; current shares fund a shared pool.</p><a href="/policies?view=fund" onClick={onLink}>Explore funding →</a></div></div></details>
 </main></div>;
}
