import {useState,useEffect} from 'react';
import {useDemo,startDemo,refreshDemo,receipt} from '../lib/demo';
const n=(v:number)=>v.toLocaleString(undefined,{maximumFractionDigits:2});
export function DemoAccount(){
 const {account:a,busy,error}=useDemo(),[copied,setCopied]=useState(false),[open,setOpen]=useState(false);
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('quorum:account',show);return()=>window.removeEventListener('quorum:account',show);},[]);
 return <details className="demo-account" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{a?<><span>Your testnet balance</span><strong className="num">{n(a.balance)} aUSDd</strong></>:<span>Your demo account</span>}</summary><div className="demo-account-body">
 <div className="eyebrow">Real testnet tokens · no cash value</div>{a?<><h3>{n(a.balance)} <small>aUSDd</small></h3><a href={`https://hashscan.io/testnet/account/${a.accountId}`} target="_blank" rel="noreferrer">Account {a.accountId} ↗</a><dl className="facts"><div><dt>Pool shares held</dt><dd>{n(a.shares)} ARPS</dd></div></dl><button className="text-button" onClick={()=>void refreshDemo()}>Refresh balances ↻</button>
 <div className="broker-box"><h4>Become a broker</h4><p>Share your link. Earn 15% of each referred premium, paid directly on testnet. The buyer pays the same premium.</p><strong className="num">Earned {n(a.commissions.reduce((sum,c)=>sum+c.amount,0))} aUSDd · {a.commissions.length} referrals</strong>{a.commissions.map(c=><div key={c.serial}><a href={receipt(c.transaction)} target="_blank" rel="noreferrer">Policy #{c.serial} · +{n(c.amount)} aUSDd ↗</a></div>)}<code>{a.referralCode}</code><button className="chip" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?ref=${a.referralCode}`);setCopied(true);}catch{setCopied(false);}}}>{copied?'Copied ✓':'Copy referral link'}</button><small>Use another browser/profile to test a referred purchase.</small></div>
 <details><summary>Your transactions</summary><a href={receipt(a.starterTx)} target="_blank" rel="noreferrer">Starter tokens ↗</a>{a.actions.map(x=><div className="account-transaction" key={x.requestId}><span>{x.kind==='deposit'?'Pool deposit':'Cover premium'} · {n(x.amount)} aUSDd</span>{x.status==='complete'&& (x.result?.depositTxId||x.result?.saleTxId)?<a href={receipt(x.result.depositTxId??x.result.saleTxId!)} target="_blank" rel="noreferrer">Verified transaction ↗</a>:<span>Needs confirmation / review</span>}</div>)}</details></>:<><h3>Try it with 1,000 aUSDd</h3><p>Create one funded testnet account for this browser. Buy cover, fund the shared pool, or earn broker commissions.</p><button className="buy" disabled={busy} onClick={()=>void startDemo()}>{busy?'Creating account…':'Start demo account →'}</button></>}
 <p className="demo-custody">Service-managed keys. This browser’s access token controls the demo account; clearing browser storage loses access. Fees are sponsored. Tokens and shares have no cash value.</p>{error?<p role="alert">{error}</p>:null}
 </div></details>;
}
