import {useEffect,useState} from 'react';
import {demoCall,refreshDemo,useDemo,receipt} from '../lib/demo';
import {useEvmDemo,startEvmDemo,refreshEvmDemo,quoteEvmDemo,executeEvmDemo,resumeEvmDemo,hasUnknownEvmOperation,demoUnits,type DemoEvmQuote} from '../lib/evm-demo';

export function DemoWalletNote(){
 const {wallet}=useEvmDemo();
 return <div className="demo-wallet-note"><span className="status-dot"/><span>Demo wallet · gas sponsored</span>{wallet?.address?<a href={`https://sepolia.etherscan.io/address/${wallet.address}`} target="_blank" rel="noreferrer">{wallet.address.slice(0,6)}…{wallet.address.slice(-4)} ↗</a>:<small>No extension needed</small>}<details><summary>About this wallet</summary><p>Real Sepolia transactions. A separate service-managed wallet for this browser, funded with test USDC and previously bridged aUSDd from the sponsor. Keys stay on the server; this browser’s access token controls the session. No cash value.</p></details></div>;
}
export function DemoOperation({kind}:{kind?:string}){
 const {wallet,error}=useEvmDemo(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const active=wallet?.actions?.find(a=>a.status==='pending'),last=active??wallet?.actions?.filter(a=>!kind||a.kind===kind).at(-1);
 const funding=wallet?.status==='funding';
 const run=async()=>{setBusy(true);setMessage('');try{if(funding)await startEvmDemo();else await resumeEvmDemo();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 if(!funding&&!last&&!hasUnknownEvmOperation()&&!error)return null;
 const steps=funding?wallet.starterSteps:last?.steps;
 return <div className="demo-operation" aria-live="polite"><span className={last?.status==='complete'?'demo-operation-ok':''}>{funding?wallet.message:last?.message??(hasUnknownEvmOperation()?'Checking the original request…':error)}</span>{steps?.length?<div className="demo-operation-steps">{steps.map(s=>s.hash?<a key={s.name} href={`https://sepolia.etherscan.io/tx/${s.hash}`} target="_blank" rel="noreferrer" title={s.name}><span aria-hidden="true">{s.status==='confirmed'?'✓':s.status==='reverted'?'×':'◌'}</span> {s.name.startsWith('gas-')||s.name==='starter-gas'?'Gas':s.name.includes('approve')?'Approval':s.name.startsWith('starter-')?'Test tokens':s.name==='liquidity'?'Position':s.name==='delivery'?'Delivery':'Swap'} ↗</a>:null)}</div>:null}{(funding||active||hasUnknownEvmOperation())&&!wallet?.running?<button className="text-button" disabled={busy} onClick={()=>void run()}>Continue original operation ↻</button>:null}{message?<small>{message}</small>:null}</div>;
}

export function DemoSwap(){
 const {wallet,busy:starting}=useEvmDemo(),[amount,setAmount]=useState('0.01'),[quote,setQuote]=useState<DemoEvmQuote|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[awaiting,setAwaiting]=useState(false);
 const active=wallet?.actions?.some(a=>a.status==='pending')||hasUnknownEvmOperation(),blocked=busy||starting||Boolean(active)||wallet?.status==='funding';
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const review=async()=>{
   if(!/^\d+(\.\d{1,2})?$/.test(amount)||Number(amount)<.01||Number(amount)>1)throw Error('Choose 0.01–1 aUSDd, up to two decimals.');
   if(wallet?.status!=='ready'){const w=await startEvmDemo();if(w.status!=='ready'){setAwaiting(true);return;}}
   setAwaiting(false);setQuote(await quoteEvmDemo('swap',{amountUnits:String(Math.round(Number(amount)*1e6))}));
 };
 useEffect(()=>{if(awaiting&&wallet?.status==='ready'&&!busy)void run(review);},[awaiting,wallet?.status,busy]);
 return <section className="testnet-swap swap-embedded"><div className="testnet-swap-body"><div className="conversion-top"><span>Sepolia · real test tokens</span><span>Gas sponsored</span></div><h2 className="flow-form-title">aUSDd → test USDC</h2><p>Try a real Uniswap swap. Approvals and testnet gas are handled for you.</p><label>Spend aUSDd<input inputMode="decimal" value={amount} disabled={blocked} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/></label>{wallet?.status==='ready'?<small>Available · {demoUnits(wallet.balance1)} aUSDd</small>:<small>Sponsored starter tokens · no wallet setup</small>}
 {!quote?<button className="buy" disabled={blocked} onClick={()=>void run(review)}>{wallet?.status==='funding'?'Preparing your demo wallet…':busy?'Getting your quote…':wallet?.status==='ready'?'Get swap quote →':'Try demo swap →'}</button>:<><div className="conversion-amounts"><div><strong>{amount}</strong><span>aUSDd</span></div><span>→</span><div><strong>{demoUnits(quote.amountOut)}</strong><span>test USDC</span></div></div><small>Minimum {demoUnits(quote.minimumOut)} test USDC · 0.5% slippage</small><button className="buy" disabled={blocked} onClick={()=>void run(async()=>{await executeEvmDemo(quote);setQuote(null);})}>Swap on Sepolia →</button><button className="text-button" disabled={blocked} onClick={()=>void run(review)}>Refresh quote ↻</button></>}
 {message?<p role="status">{message}</p>:null}<DemoOperation kind="swap"/></div></section>;
}

export function DemoLiquidity(){
 const {wallet,busy:starting}=useEvmDemo(),[selected,setSelected]=useState('new'),[mode,setMode]=useState<'add'|'collect'|'remove'>('add'),[amount,setAmount]=useState('0.01'),[percentage,setPercentage]=useState(100),[quote,setQuote]=useState<DemoEvmQuote|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const position=wallet?.positions?.find(p=>p.tokenId===selected),latest=wallet?.actions?.filter(a=>a.kind==='lp').at(-1);
 const active=wallet?.actions?.some(a=>a.status==='pending')||hasUnknownEvmOperation(),blocked=busy||starting||Boolean(active);
 useEffect(()=>{if(latest?.status==='complete'&&latest.result?.tokenId){setSelected(latest.result.tokenId);setQuote(null);}},[latest?.requestId,latest?.status]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const review=async()=>{
   if(mode==='add'&&(!/^\d+(\.\d{1,2})?$/.test(amount)||Number(amount)<.01||Number(amount)>1))throw Error('Choose 0.01–1 aUSDd.');
   const action=mode==='add'?(selected==='new'?'create':'increase'):mode;
   setQuote(await quoteEvmDemo('lp',{action,...(action==='create'?{}:{tokenId:selected}),...(mode==='add'?{amountUnits:String(Math.round(Number(amount)*1e6))}:mode==='remove'?{percentage}:{})}));
 };
 return <><div className="liquidity-account-bar"><h3>Your demo position</h3>{wallet?.address?<a href={`https://sepolia.etherscan.io/address/${wallet.address}`} target="_blank" rel="noreferrer">Demo wallet ↗</a>:null}{wallet?.status==='ready'?<button className="text-button" disabled={busy} onClick={()=>void run(refreshEvmDemo)}>Refresh ↻</button>:null}</div>
 {wallet?.status!=='ready'?<><p>Test tokens and gas supplied. No extension or wallet connection.</p><button className="buy" disabled={blocked||wallet?.status==='funding'} onClick={()=>void run(startEvmDemo)}>{wallet?.status==='funding'?'Preparing your demo wallet…':'Start with test tokens →'}</button></>:<div className="liquidity-manage-grid"><div className="liquidity-position"><label>Position<select value={selected} disabled={blocked} onChange={e=>{setSelected(e.target.value);setMode('add');setQuote(null);}}><option value="new">Create a position NFT</option>{wallet.positions?.map(p=><option key={p.tokenId} value={p.tokenId}>NFT #{p.tokenId}{p.liquidity==='0'?' · removed':''}</option>)}</select></label>
 {position?<><div className="liquidity-position-top"><strong>NFT #{position.tokenId}</strong><a href={`https://sepolia.etherscan.io/nft/0x1238536071e1c677a632429e3655c799b22cda52/${position.tokenId}`} target="_blank" rel="noreferrer">Verify NFT ↗</a></div><div className="liquidity-position-values"><div><span>In position</span><strong>{demoUnits(position.amount1)} aUSDd</strong><strong>{demoUnits(position.amount0)} test USDC</strong></div><div><span>Uncollected</span><strong className="liquidity-earned">{demoUnits(position.claimable1)} aUSDd</strong><strong className="liquidity-earned">{demoUnits(position.claimable0)} test USDC</strong></div></div><small>{position.liquidity==='0'?'Position withdrawn':position.inRange?'In range · swap fees accrue here':'Out of range'}</small></>:<div className="liquidity-new-position"><span aria-hidden="true">∞</span><strong>Full-range liquidity</strong><p>Two tokens in. A real Uniswap NFT for this demo wallet.</p></div>}</div>
 <div className="liquidity-actions"><div className="liquidity-action-tabs" role="group" aria-label="Demo position action">{(['add','collect','remove'] as const).map(x=><button key={x} aria-pressed={mode===x} disabled={blocked||(x!=='add'&&!position)} onClick={()=>{setMode(x);setQuote(null);}}>{x==='add'?'Add liquidity':x==='collect'?'Collect fees':'Remove'}</button>)}</div>
 {mode==='add'?<label>Add aUSDd<input value={amount} inputMode="decimal" disabled={blocked} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/><small>Plus matching test USDC · gas sponsored</small></label>:mode==='remove'?<label>Remove from this position<select value={percentage} disabled={blocked} onChange={e=>{setPercentage(Number(e.target.value));setQuote(null);}}>{[25,50,100].map(p=><option key={p} value={p}>{p}%{p===100?' · exit position':''}</option>)}</select></label>:<p>Collect available fees. Your liquidity stays in the pool.</p>}
 <small className="liquidity-wallet-balance">Demo balance · {demoUnits(wallet.balance1)} aUSDd · {demoUnits(wallet.balance0)} test USDC</small>
 {!quote?<button className="buy" disabled={blocked||(Boolean(position)&&!position?.supported)||!wallet.balancesAvailable||(mode==='remove'&&position?.liquidity==='0')||(mode==='collect'&&position?.claimable0==='0'&&position?.claimable1==='0')} onClick={()=>void run(review)}>{busy?'Checking on-chain…':mode==='add'?'Review liquidity →':mode==='remove'?'Review withdrawal →':'Review fees →'}</button>:<div className="liquidity-review"><span>{mode==='add'?'You provide':'Tokens returned'}</span><strong>{demoUnits(quote.amount1)} aUSDd <span>+</span> {demoUnits(quote.amount0)} test USDC</strong><small>{mode==='add'?`Up to ${demoUnits(quote.maximum0)} test USDC · `:''}0.5% slippage · gas sponsored</small><button className="buy" disabled={blocked} onClick={()=>void run(async()=>{await executeEvmDemo(quote);setQuote(null);})}>{mode==='add'?'Add liquidity on Sepolia →':mode==='remove'?'Withdraw to demo wallet →':'Collect to demo wallet →'}</button><button className="text-button" disabled={blocked} onClick={()=>void run(review)}>Refresh review ↻</button></div>}
 </div></div>}
 {message?<p role="status">{message}</p>:null}<DemoOperation kind="lp"/><details className="liquidity-explainer"><summary>Wallet, fees & protection <span>+</span></summary><p>This browser controls a separate service-managed Sepolia wallet. Approvals use exact amounts; signing is restricted to this market and your own position. Keys remain on the server. No ARPS or cover reserves are used.</p><p>Swap fees are actual token amounts, not an APY. The token mix can change. Uncollected amounts may include previously removed principal. Test tokens have no cash value.</p></details></>;
}

export function DemoBridge({onSwap}:{onSwap:()=>void}){
 const {wallet}=useEvmDemo(),{account}=useDemo(),[amount,setAmount]=useState('0.01'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState<any>(null),[awaiting,setAwaiting]=useState(false);
 const KEY='quorum.demo.bridge.request';
 const latest=account?.actions.filter(a=>a.kind==='bridge'&&a.status==='complete'&&a.recipient?.toLowerCase()===wallet?.address).at(-1);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{let active=true;setStatus(null);if(!latest)return;const check=()=>demoCall('/api/demo/bridge/status?requestId='+encodeURIComponent(latest.requestId)).then(s=>{if(active)setStatus(s);}).catch(()=>{});void check();const timer=setInterval(()=>void check(),12000);return()=>{active=false;clearInterval(timer);};},[latest?.requestId,wallet?.address]);
 const send=async()=>{
   if(!/^\d+(\.\d{1,2})?$/.test(amount)||Number(amount)<.01||Number(amount)>10)throw Error('Bridge 0.01–10 aUSDd.');
   if(wallet?.status!=='ready'){const w=await startEvmDemo();if(w.status!=='ready'){setAwaiting(true);return;}}
   setAwaiting(false);const previous=localStorage.getItem(KEY),request=previous?JSON.parse(previous):{requestId:crypto.randomUUID(),amount:Number(amount)};
   localStorage.setItem(KEY,JSON.stringify(request));
   try{await demoCall('/api/demo/evm/bridge',request);localStorage.removeItem(KEY);setMessage('Source confirmed. Axelar is delivering your tokens.');await refreshDemo();}
   catch(e){if((e as {status?:number}).status){try{const view=await demoCall('/api/demo');if(!view.actions.some((a:{requestId:string})=>a.requestId===request.requestId))localStorage.removeItem(KEY);}catch{/* Preserve unknown request. */}}throw e;}
 };
 useEffect(()=>{if(awaiting&&wallet?.status==='ready'&&!busy)void run(send);},[awaiting,wallet?.status,busy]);
 return <section className="testnet-swap swap-embedded"><div className="testnet-swap-body"><h2 className="flow-form-title">Move aUSDd to Sepolia</h2><p>Bridge from your Hedera demo account to your demo wallet. Gas is sponsored on both sides.</p><label>Bridge aUSDd<input value={amount} inputMode="decimal" disabled={busy||Boolean(localStorage.getItem(KEY))} onChange={e=>setAmount(e.target.value)}/></label><small>{account?`${account.balance.toLocaleString()} aUSDd on Hedera`:'Hedera starter tokens included with your first bridge'}</small><button className="buy" disabled={busy||wallet?.status==='funding'} onClick={()=>void run(send)}>{busy?'Preparing your bridge…':localStorage.getItem(KEY)?'Reconcile original bridge ↻':'Bridge test tokens →'}</button>
 {latest?<div className="testnet-swap-receipt"><strong>{status?.status==='delivered'?'✓ Delivered to your demo wallet':status?.status==='ready-to-deliver'?'Approved · ready to deliver':'Axelar delivery in progress'}</strong><a href={receipt(latest.result!.bridgeTxId!)} target="_blank" rel="noreferrer">Hedera receipt ↗</a>{status?.explorer?<a href={status.explorer} target="_blank" rel="noreferrer">Track Axelar ↗</a>:null}{status?.destinationHash?<a href={`https://sepolia.etherscan.io/tx/${status.destinationHash}`} target="_blank" rel="noreferrer">Sepolia receipt ↗</a>:null}{status?.status==='ready-to-deliver'?<button className="chip" disabled={busy||wallet?.actions?.some(a=>a.status==='pending')} onClick={()=>void run(async()=>{const q=await quoteEvmDemo('delivery',{bridgeRequestId:latest.requestId});await executeEvmDemo(q);})}>Complete sponsored delivery →</button>:null}{status?.status==='delivered'?<button className="buy" onClick={onSwap}>Continue to Uniswap swap →</button>:null}</div>:null}
 {message?<p role="status">{message}</p>:null}<DemoOperation kind="delivery"/></div></section>;
}
