import {useState,useEffect} from 'react';
import {useDemo,startDemo,demoCall,refreshDemo,receipt} from '../lib/demo';
import {useAgent,refresh} from '../lib/store';
import {fetchToken} from '../lib/mirror';
export function FundPool(){
 const a=useAgent(),pool=a.pool,{account,busy:starting,error}=useDemo();
 const [amount,setAmount]=useState(()=>Number(localStorage.getItem('quorum.pending.deposit.amount')??25)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tx,setTx]=useState('');
 const [id,setId]=useState(()=>localStorage.getItem('quorum.pending.deposit')??crypto.randomUUID());
 useEffect(()=>{if(!localStorage.getItem('quorum.pending.deposit'))return;const action=account?.actions.find(x=>x.requestId===id);if(action?.status==='complete'&&action.result?.depositTxId){setTx(action.result.depositTxId);setMessage(`${action.amount} aUSDd deposited · ${action.result.shares??action.amount} ARPS received`);localStorage.removeItem('quorum.pending.deposit');localStorage.removeItem('quorum.pending.deposit.amount');setId(crypto.randomUUID());}},[account,id]);
 const [supply,setSupply]=useState<number|null>(null);
 useEffect(()=>{
  let active=true;setSupply(null);
  if(account) void fetchToken(account.shareTokenId,'testnet').then(t=>{
   const total=Number(t.totalSupply)/10**t.decimals;
   if(active&&Number.isFinite(total)&&total>0) setSupply(total);
  }).catch(()=>{});
  return()=>{active=false;};
 },[account?.shareTokenId,account?.checkedAt]);
 const sharePercent=supply!==null&&account&&account.shares<=supply?account.shares/supply*100:null;
 const latestDeposit=account?.actions.filter(x=>x.kind==='deposit'&&x.status==='complete'&&x.result?.depositTxId).at(-1);
 const n=(v:number)=>v.toLocaleString(undefined,{maximumFractionDigits:2});
 const fund=async()=>{setBusy(true);setMessage('');try{localStorage.setItem('quorum.pending.deposit',id);localStorage.setItem('quorum.pending.deposit.amount',String(amount));const r=await demoCall('/api/demo/deposit',{amount,requestId:id});setTx(r.depositTxId);setMessage(`${n(r.amount)} aUSDd deposited · ${n(r.shares)} ARPS received`);localStorage.removeItem('quorum.pending.deposit');localStorage.removeItem('quorum.pending.deposit.amount');setId(crypto.randomUUID());await Promise.all([refreshDemo(),refresh()]);}catch(e){setMessage((e as Error).message);if((e as Error & {status?:number}).status){try{const view=await demoCall('/api/demo');if(!view.actions.some((x:{requestId:string})=>x.requestId===id)){localStorage.removeItem('quorum.pending.deposit');localStorage.removeItem('quorum.pending.deposit.amount');setId(crypto.randomUUID());}}catch{/* Keep unknown deposits blocked. */}}void refreshDemo();}finally{setBusy(false);}};
 return <><section className="fund-pool" aria-label="Fund the shared pool"><div><div className="eyebrow">Real testnet deposit</div><h2>Back the shared pool.</h2><p>One aUSDd deposit. Many aUSDd policies.</p>{account&&account.shares>0?<section className="lp-position" aria-label="Your pool position"><div className="capital-heading"><span>Your pool position</span><a href={`https://hashscan.io/testnet/account/${account.accountId}`} target="_blank" rel="noreferrer">View ARPS ↗</a></div><div className="lp-position-values"><div><strong className="num">{n(account.shares)}</strong><span>ARPS held</span></div><div><strong className="num">{sharePercent===null?'—':`${sharePercent.toLocaleString(undefined,{maximumFractionDigits:4})}%`}</strong><span>of issued ARPS</span></div></div><div className="lp-position-meter" aria-hidden="true"><span style={{width:`${sharePercent??0}%`}}/></div><small>Earnings distributions · not enabled</small><details><summary>What does my % mean?</summary><p>Your ARPS ÷ all issued ARPS. This is a token holding percentage, not an APY or a claim on that percentage of pool assets. Demo shares use a fixed 1:1 deposit rule.</p><p>Returns would depend on premiums minus claims and costs. This demo has no withdrawals or investment income distributions.</p>{supply!==null?<small>{n(supply)} ARPS issued · <a href={`https://hashscan.io/testnet/token/${account.shareTokenId}`} target="_blank" rel="noreferrer">Verify supply ↗</a></small>:<small>Share percentage unavailable while live supply is loading or unreachable.</small>}</details>{latestDeposit?<a href={receipt(latestDeposit.result!.depositTxId!)} target="_blank" rel="noreferrer">Latest deposit receipt ↗</a>:null}</section>:null}<div className="pool-business-map" aria-label="Your deposit funds one shared pool backing many policies"><span>You<small>aUSDd deposit</small></span><i aria-hidden="true">→</i><strong>Shared pool<small>ARPS for you</small></strong><i aria-hidden="true">→</i><span>Many policies<small>Shared capital</small></span></div><div className="capital-values">{[['Pool capital',pool?.capital],['Reserved for payouts',pool?.committed],['Free to back new cover',pool?.headroom]].map(([label,v])=><div key={label}><span>{label}</span><strong className="num">{typeof v==='number'?n(v):'—'}</strong></div>)}</div><small>{pool?`${pool.livePolicies} aUSDd obligations · ${n(pool.capital>0?pool.committed/pool.capital*100:0)}% of capital reserved`:null}</small><small>aUSDd · {a.poolAt?`checked ${new Date(a.poolAt).toLocaleTimeString()}`:'balance unavailable'} · <a href={pool?.hashscan??'https://hashscan.io/testnet'} target="_blank" rel="noreferrer">Verify pool ↗</a></small></div>
 <div className="fund-pool-action">{account?<><div className="capital-heading"><span>Your balance</span><strong>{n(account.balance)} aUSDd</strong></div><label>Deposit amount <input type="number" min={1} max={Math.min(100,account.balance)} step={1} value={amount} disabled={busy||Boolean(localStorage.getItem('quorum.pending.deposit'))} onChange={e=>{setAmount(Number(e.target.value));if(!localStorage.getItem('quorum.pending.deposit'))setId(crypto.randomUUID());}}/></label><small>1–100 aUSDd per deposit · 12 account actions per day</small><div className="fund-shares">{n(amount)} aUSDd <span>→</span> {n(amount)} ARPS</div><p className="funding-limit">Testnet only · no withdrawals or LP income</p><button className="buy" disabled={busy||!a.online||!Number.isFinite(amount)||amount<1||amount>100||amount>account.balance} onClick={()=>void fund()}>{busy?'Waiting for Hedera…':localStorage.getItem('quorum.pending.deposit')?'Check original deposit ↻':'Deposit into shared pool →'}</button></>:<button className="buy" disabled={starting||!a.online} onClick={()=>void startDemo()}>{starting?'Creating your account…':'Get testnet tokens to fund →'}</button>}
 <small>Fixed 1:1 demo shares · not priced from the pool’s assets.</small>{message||error?<p role="status">{message||error}</p>:null}{tx?<a href={receipt(tx)} target="_blank" rel="noreferrer">Verify deposit and shares ↗</a>:null}
 </div></section><details className="business-flow"><summary>How this business works <span>+</span></summary><div className="business-flow-grid"><div><strong>Buyer →</strong><span>Pays a premium for a fixed conditional payout.</span></div><div><strong>85% / 15%</strong><span>With a referral: pool / broker. Without one: 100% to pool.</span></div><div><strong>Pool →</strong><span>Holds deposits and premiums; qualifying payouts consume capital.</span></div></div><p><strong>Premium</strong> = price paid for cover. <strong>Payout</strong> = amount sent if the earthquake conditions are met. <strong>Pool</strong> = shared funds backing many policies. <strong>Broker</strong> = someone who refers a buyer.</p><p>Pool balance includes deposits, operator top-ups and premiums; it is not profit. Free capacity = balance minus all active payouts in the same asset. Legacy HBAR cover is accounted for separately. Investment returns depend on earned premiums minus claims and costs. Demo shares are real, but withdrawals and income distributions are not implemented. Oracle query payments are a separate service expense, not a claim approval.</p><button className="text-button" onClick={()=>window.dispatchEvent(new Event('quorum:account'))}>Get your broker referral link ↗</button>
 <section className="business-next" aria-label="Proposed commercial model">
   <div className="eyebrow">Beyond the demo · proposed</div>
   <div className="business-next-roles"><div><strong>Brokers</strong><span>Distribution</span></div><div><strong>Insurers</strong><span>Risk backing</span></div><div><strong>Quorum</strong><span>Policy operations</span></div></div>
   <p>Revenue to validate: partner subscriptions and per-policy service fees.</p>
   <small>Next: one region, risk-model validation and an insurance partner. No platform fee is charged today.</small>
 </section></details></>;
}
