import {useState} from 'react';
import {useDemo,startDemo,demoCall,refreshDemo,receipt} from '../lib/demo';
import {useAgent,refresh} from '../lib/store';
export function FundPool(){
 const a=useAgent(),pool=a.pool,{account,busy:starting,error}=useDemo();
 const [amount,setAmount]=useState(()=>Number(localStorage.getItem('quorum.pending.deposit.amount')??25)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tx,setTx]=useState('');
 const [id,setId]=useState(()=>localStorage.getItem('quorum.pending.deposit')??crypto.randomUUID());
 const n=(v:number)=>v.toLocaleString(undefined,{maximumFractionDigits:2});
 const fund=async()=>{setBusy(true);setMessage('');try{localStorage.setItem('quorum.pending.deposit',id);localStorage.setItem('quorum.pending.deposit.amount',String(amount));const r=await demoCall('/api/demo/deposit',{amount,requestId:id});setTx(r.depositTxId);setMessage(`${n(r.amount)} aUSDd deposited · ${n(r.shares)} ARPS received`);localStorage.removeItem('quorum.pending.deposit');localStorage.removeItem('quorum.pending.deposit.amount');setId(crypto.randomUUID());await Promise.all([refreshDemo(),refresh()]);}catch(e){setMessage((e as Error).message);if([400,401,429].includes((e as Error & {status?:number}).status??0)){localStorage.removeItem('quorum.pending.deposit');localStorage.removeItem('quorum.pending.deposit.amount');setId(crypto.randomUUID());}void refreshDemo();}finally{setBusy(false);}};
 return <><section className="fund-pool" aria-label="Fund the shared pool"><div><div className="eyebrow">Real testnet deposit</div><h2>Back the shared pool.</h2><p>Anyone can contribute. Your tokens support cover across all policies; you receive pool-share tokens (ARPS).</p><div className="capital-values">{[['Pool capital',pool?.capital],['Promised payouts',pool?.committed],['Free to back new cover',pool?.headroom]].map(([label,v])=><div key={label}><span>{label}</span><strong className="num">{typeof v==='number'?n(v):'—'}</strong></div>)}</div><small>aUSDd · {a.poolAt?`checked ${new Date(a.poolAt).toLocaleTimeString()}`:'balance unavailable'} · <a href={pool?.hashscan??'https://hashscan.io/testnet'} target="_blank" rel="noreferrer">Verify pool ↗</a></small></div>
 <div className="fund-pool-action">{account?<><div className="capital-heading"><span>Your balance</span><strong>{n(account.balance)} aUSDd</strong></div><label>Deposit amount <input type="number" min={1} max={Math.min(100,account.balance)} step={1} value={amount} disabled={busy||Boolean(localStorage.getItem('quorum.pending.deposit'))} onChange={e=>{setAmount(Number(e.target.value));if(!localStorage.getItem('quorum.pending.deposit'))setId(crypto.randomUUID());}}/></label><small>1–100 aUSDd per deposit · 12 account actions per day</small><div className="fund-shares">{n(amount)} aUSDd <span>→</span> {n(amount)} ARPS</div><button className="buy" disabled={busy||!a.online||!Number.isFinite(amount)||amount<1||amount>100||amount>account.balance} onClick={()=>void fund()}>{busy?'Waiting for Hedera…':'Deposit into shared pool →'}</button></>:<button className="buy" disabled={starting} onClick={()=>void startDemo()}>{starting?'Creating your account…':'Get testnet tokens to fund →'}</button>}
 <small>Demo rule: 1 aUSDd buys 1 pool share (ARPS). Shares are not priced from the pool’s assets. You cannot withdraw deposits or collect investment income in this demo.</small>{message||error?<p role="status">{message||error}</p>:null}{tx?<a href={receipt(tx)} target="_blank" rel="noreferrer">Verify deposit and shares ↗</a>:null}
 </div></section><details className="business-flow"><summary>How this business works <span>+</span></summary><div className="business-flow-grid"><div><strong>Buyer →</strong><span>Pays a premium for a fixed conditional payout.</span></div><div><strong>85% / 15%</strong><span>With a referral: pool / broker. Without one: 100% to pool.</span></div><div><strong>Pool →</strong><span>Holds deposits and premiums; qualifying payouts consume capital.</span></div></div><p><strong>Premium</strong> = price paid for cover. <strong>Payout</strong> = amount sent if the earthquake conditions are met. <strong>Pool</strong> = shared funds backing many policies. <strong>Broker</strong> = someone who refers a buyer.</p><p>Investment returns depend on premiums minus claims and costs. Demo shares are real, but withdrawals and income distributions are not implemented. The app currently takes no separate platform fee. Oracle query payments are a separate service expense, not a claim approval.</p><button className="text-button" onClick={()=>window.dispatchEvent(new Event('quorum:account'))}>Get your broker referral link ↗</button></details></>;
}
